# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiagnosticsTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Sentry', '~> 8'

  # Pods for DiagnosticsTool

  target 'DiagnosticsToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiagnosticsToolUITests' do
    # Pods for testing
  end

end
